import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import icon from "@/public/assets/treeIcon512.png";
import Category from "@/components/Category";
import Breadcrumb from "@/components/Breadcrumb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hvilket tre er det?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen p-4">
        <header className="flex items-center gap-4">
          <Link href="/">
            <Image src={icon} alt="logo" width={128} height={128} />
          </Link>
          <h1 className={`${inter.className} font-mono`}>Norske Trær</h1>
        </header>
        <Breadcrumb />
        <main className="flex flex-col items-center justify-between mx-20 my-10">
          {children}
        </main>
      </body>
    </html>
  );
}
